class ResourceConflictError(Exception):
    """raised when call is unsuccessful"""
    pass